version: '3.9'

services:
  archiver:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    read_only: false
    volumes:
      - ./:/app:rw
    ports:
      - 8099:4567
    expose:
      - 8099
    command: 'ruby app.rb'

networks:
  default:
    name: internet-archive
