development:
  adapter: sqlite3
  database: db/archive_dev_sqlite3.db
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/archive_test_sqlite3.db
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/archive_prod_sqlite3.db
  pool: 5
  timeout: 5000
